[server]
host = "172.16.0.4"
port = 4443
enable_https = false
pem_cert_path = "configuration/server/ssl/cert.pem"
pem_key_path = "configuration/server/ssl/.key"
domain = "discord-sucks.usiiaa.top"

[cloudflare]
turnstile_secret_key_path = "configuration/server/turnstile_secret.txt"
allow_invalid_turnstile = false
allow_non_cloudflare_ips = true
cloudflare_ips_refresh_interval_s = 5
cloudflare_ips_refresh_interval_jitter_s = 10

[smtp]
smtp_username = "postmaster@email.discord-sucks.usiiaa.top"
smtp_password_path = "configuration/server/smtp_password.txt"
smtp_host = "smtp.eu.mailgun.org"

[verification_email]
email_sender_name = "Discord Sucks"
email_sender_email_address = "verification@email.discord-sucks.usiiaa.top"
email_subject = "Discord-Sucks verify your email address"
verification_url_domain = "https://discord-sucks.usiiaa.top"
verification_url_endpoint = "/verify_email"
email_verification_jwt_lifetime_s = 300

[jwt]
refresh_key_lifetime_s = 1000
access_key_lifetime_s = 300
jwt_secret_path = "configuration/server/jwt_secret.txt"

[password_requirements]
min_length = 12
max_length = 64
must_contain_uppercase = true
must_contain_symbol = true
must_contain_number = true
ascii_only = true
no_special_characters = true
no_whitespaces = true


[postgres_database]
username = "admin"
password = "password123"
host = "127.0.0.1"
port = 5432
database_name = "discord_sucks"
max_connections = 10

[redis_database]
host = "127.0.0.1"
port = 6379
