[server]
host = "172.16.0.4"
port = 4443
enable_https = false
allow_non_cloudflare_ips = true
cloudflare_ips_refresh_interval_s = 5
cloudflare_ips_refresh_interval_jitter_s = 10
pem_cert_path = "configuration/server/ssl/cert.pem"
pem_key_path = "configuration/server/ssl/.key"
jwt_secret_path = "configuration/server/jwt_secret.txt"

[metrics_server]
host = "172.16.0.4"
port = 3001


[postgres_database]
username = "admin"
password = "password123"
host = "127.0.0.1"
port = 5432
database_name = "discord_sucks"
max_connections = 10

[redis_database]
host = "127.0.0.1"
port = 6379
