[server]
host = "172.16.0.4"
port = 4443
enable_https = false
allow_non_cloudflare_ips = true
cloudflare_ips_refresh_interval_s = 5
cloudflare_ips_refresh_interval_jitter_s = 10
pem_cert_path = "configuration/server/ssl/cert.pem"
pem_key_path = "configuration/server/ssl/.key"

[jwt]
refresh_key_lifetime_s = 1000
access_key_lifetime_s = 300
jwt_secret_path = "configuration/server/jwt_secret.txt"

[password_requirements]
min_length = 12
max_length = 64
must_contain_uppercase = true
must_contain_symbol = true
must_contain_number = true
ascii_only = true
no_special_characters = true
no_whitespaces = true


[postgres_database]
username = "admin"
password = "password123"
host = "127.0.0.1"
port = 5432
database_name = "discord_sucks"
max_connections = 10

[redis_database]
host = "127.0.0.1"
port = 6379
