version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres-discord-sucks
    ports:
      - 5432:5432
    volumes:
      - ../db-data/postgres:/var/lib/postgresql/data
    env_file:
      - ./postgres.env

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./postgres.env
    ports:
      - "5050:80"
  
  redis:
    image: redis:latest
    container_name: redis-discord-sucks
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ../db-data/redis_data:/root/redis
      - ../db-data/redis_data/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ./redis.env

